import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { getServerSession, Session } from "next-auth";
import NextSessionProvider from "./sessionProvider";
import { useParams } from "next/navigation";
import authOptions from "@/lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const Navbar = dynamic(() => import("@/modules/navbar"), { ssr: false });

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <NextSessionProvider>
         <html lang="en">
            <body className={inter.className}>{children}</body>
         </html>
      </NextSessionProvider>
   );
}
